/* ============================================================
   SOL-NET DATA CORE
   All figures are approximate, sourced from public NASA/JPL
   planetary fact sheets. Distances are average (semi-major axis).
   ============================================================ */

const C_KM_S = 299792.458; // speed of light, km/s
const G = 6.6743e-11; // gravitational constant, m^3 kg^-1 s^-2

// Helper: light travel time in human readable string from distance in km
function lightTime(km) {
  const seconds = (km / C_KM_S);
  if (seconds < 60) return seconds.toFixed(1) + " sec";
  const minutes = seconds / 60;
  if (minutes < 60) return minutes.toFixed(1) + " min";
  const hours = minutes / 60;
  if (hours < 24) return hours.toFixed(2) + " hr";
  const days = hours / 24;
  if (days < 365) return days.toFixed(2) + " days";
  return (days / 365.25).toFixed(2) + " yrs";
}

/* color: base render color, ring: has saturn-like ring,
   orbitRadius: scaled scene units (not to real scale - log-ish compressed),
   size: scaled render radius, speed: relative orbital speed in scene */
const BODIES = [
  {
    id: "sun",
    type: "STAR",
    name: "THE SUN",
    tagline: "G2V Yellow Dwarf — the engine room of the entire system.",
    classification: "PRIMARY // UNCLASSIFIED",
    color: 0xffd34d,
    emissive: 0xffae00,
    size: 5.6,
    orbitRadius: 0,
    speed: 0,
    note: "Every 8 minutes and 20 seconds of sunlight you feel left the Sun's surface before you were even aware of it — that's how long light takes to reach Earth.",
    stats: [
      ["Diameter", "1,392,700 km (109 × Earth)"],
      ["Mass", "1.989 × 10³⁰ kg (333,000 × Earth)"],
      ["Core Temp", "≈ 15,000,000 °C"],
      ["Surface Temp", "≈ 5,500 °C"],
      ["Rotation", "≈ 25–35 days (differential)"],
      ["Composition", "73% Hydrogen, 25% Helium, 2% other"],
      ["Age", "≈ 4.6 billion years"],
      ["Light → Earth", "8 min 20 sec"],
    ],
  },
  {
    id: "mercury",
    type: "PLANET I",
    name: "MERCURY",
    tagline: "Smallest planet, scorched by day, frozen by night.",
    classification: "ROCKY // INNER SYSTEM",
    color: 0x9a9a92,
    emissive: 0x222018,
    size: 0.9,
    orbitRadius: 11,
    speed: 1.6,
    note: "No atmosphere to trap heat means a single Mercurian day swings from 430°C to −180°C.",
    distanceKm: 57.9e6,
    stats: [
      ["Distance from Sun", "57.9 million km (0.39 AU)"],
      ["Light Travel Time", lightTime(57.9e6)],
      ["Orbital Period", "88 Earth days"],
      ["Day Length (rotation)", "59 Earth days"],
      ["Diameter", "4,879 km"],
      ["Moons", "0"],
      ["Core Temp (est.)", "≈ 4,000 °C"],
      ["Surface Temp", "−180 °C to 430 °C"],
      ["Mass", "3.30 × 10²³ kg"],
      ["Surface Gravity", "3.7 m/s²"],
    ],
  },
  {
    id: "venus",
    type: "PLANET II",
    name: "VENUS",
    tagline: "Earth's toxic twin — a runaway greenhouse under sulfuric clouds.",
    classification: "ROCKY // INNER SYSTEM",
    color: 0xe8c989,
    emissive: 0x4a3514,
    size: 1.3,
    orbitRadius: 15,
    speed: 1.2,
    note: "Venus rotates backwards (retrograde) so slowly that one day there lasts longer than its entire year.",
    distanceKm: 108.2e6,
    stats: [
      ["Distance from Sun", "108.2 million km (0.72 AU)"],
      ["Light Travel Time", lightTime(108.2e6)],
      ["Orbital Period", "225 Earth days"],
      ["Day Length (rotation)", "243 Earth days (retrograde)"],
      ["Diameter", "12,104 km"],
      ["Moons", "0"],
      ["Core Temp (est.)", "≈ 5,000 °C"],
      ["Surface Temp", "≈ 465 °C (hottest planet)"],
      ["Mass", "4.87 × 10²⁴ kg"],
      ["Surface Gravity", "8.87 m/s²"],
    ],
  },
  {
    id: "earth",
    type: "PLANET III",
    name: "EARTH",
    tagline: "Home. The only known body harboring life.",
    classification: "ROCKY // HABITABLE",
    color: 0x3b82c4,
    emissive: 0x0a2436,
    size: 1.4,
    orbitRadius: 19,
    speed: 1.0,
    note: "1 AU — the distance from Earth to the Sun — is the ruler astronomers use to measure the rest of the solar system.",
    distanceKm: 149.6e6,
    stats: [
      ["Distance from Sun", "149.6 million km (1 AU, by definition)"],
      ["Light Travel Time", lightTime(149.6e6)],
      ["Orbital Period", "365.25 days"],
      ["Day Length (rotation)", "23 hr 56 min"],
      ["Diameter", "12,742 km"],
      ["Moons", "1 (The Moon)"],
      ["Core Temp", "≈ 5,400 °C (inner core)"],
      ["Surface Temp (avg)", "≈ 15 °C"],
      ["Mass", "5.97 × 10²⁴ kg"],
      ["Surface Gravity", "9.81 m/s²"],
    ],
  },
  {
    id: "mars",
    type: "PLANET IV",
    name: "MARS",
    tagline: "The Red Planet — rust-colored dust, ancient riverbeds, two tiny moons.",
    classification: "ROCKY // OUTER FRONTIER",
    color: 0xc1551f,
    emissive: 0x3a1206,
    size: 1.0,
    orbitRadius: 24,
    speed: 0.8,
    note: "Phobos and Deimos are likely captured asteroids, not formed alongside Mars — both are irregular, lumpy, and tiny.",
    distanceKm: 227.9e6,
    stats: [
      ["Distance from Sun", "227.9 million km (1.52 AU)"],
      ["Light Travel Time", lightTime(227.9e6)],
      ["Orbital Period", "687 Earth days"],
      ["Day Length (rotation)", "24 hr 37 min"],
      ["Diameter", "6,779 km"],
      ["Moons", "2 — Phobos & Deimos (captured asteroids)"],
      ["Core Temp (est.)", "≈ 1,500–2,000 °C, partly molten"],
      ["Surface Temp (avg)", "≈ −65 °C"],
      ["Mass", "6.42 × 10²³ kg"],
      ["Surface Gravity", "3.71 m/s²"],
    ],
  },
  {
    id: "jupiter",
    type: "PLANET V",
    name: "JUPITER",
    tagline: "The system's bodyguard — a gas giant with 95 known moons.",
    classification: "GAS GIANT // OUTER SYSTEM",
    color: 0xd9b08c,
    emissive: 0x3a2a18,
    size: 3.6,
    orbitRadius: 33,
    speed: 0.45,
    note: "Jupiter's gravity has flung countless comets and asteroids out of Earth's path over the eons — an unintentional shield.",
    distanceKm: 778.5e6,
    stats: [
      ["Distance from Sun", "778.5 million km (5.20 AU)"],
      ["Light Travel Time", lightTime(778.5e6)],
      ["Orbital Period", "11.86 years"],
      ["Day Length (rotation)", "9 hr 56 min — fastest spin in the system"],
      ["Diameter", "139,820 km (11 × Earth)"],
      ["Moons", "95 known — incl. 4 Galilean moons (Io, Europa, Ganymede, Callisto)"],
      ["Core Temp (est.)", "≈ 24,000 °C"],
      ["Cloud-top Temp", "≈ −145 °C"],
      ["Mass", "1.898 × 10²⁷ kg"],
      ["Surface Gravity", "24.79 m/s²"],
    ],
  },
  {
    id: "saturn",
    type: "PLANET VI",
    name: "SATURN",
    tagline: "Ringed jewel of the system, light enough to float in water.",
    classification: "GAS GIANT // OUTER SYSTEM",
    color: 0xe3cf9d,
    emissive: 0x3a3015,
    size: 3.1,
    ring: true,
    orbitRadius: 42,
    speed: 0.33,
    note: "Saturn's average density is lower than water's — if you could find an ocean big enough, the planet would float.",
    distanceKm: 1433.5e6,
    stats: [
      ["Distance from Sun", "1.434 billion km (9.58 AU)"],
      ["Light Travel Time", lightTime(1433.5e6)],
      ["Orbital Period", "29.4 years"],
      ["Day Length (rotation)", "10 hr 42 min"],
      ["Diameter", "116,460 km"],
      ["Moons", "146 known — Titan (largest, has a thick atmosphere) leads the pack"],
      ["Core Temp (est.)", "≈ 11,700 °C"],
      ["Cloud-top Temp", "≈ −178 °C"],
      ["Mass", "5.68 × 10²⁶ kg"],
      ["Surface Gravity", "10.44 m/s²"],
    ],
  },
  {
    id: "uranus",
    type: "PLANET VII",
    name: "URANUS",
    tagline: "An ice giant tipped on its side, spinning almost like a rolling ball.",
    classification: "ICE GIANT // FAR SYSTEM",
    color: 0x8fd6d9,
    emissive: 0x123537,
    size: 2.1,
    ring: true,
    orbitRadius: 50,
    speed: 0.23,
    note: "Uranus's axial tilt of 98° means its poles take turns facing the Sun directly for 21-year-long seasons.",
    distanceKm: 2872.5e6,
    stats: [
      ["Distance from Sun", "2.873 billion km (19.2 AU)"],
      ["Light Travel Time", lightTime(2872.5e6)],
      ["Orbital Period", "84 years"],
      ["Day Length (rotation)", "17 hr 14 min (retrograde)"],
      ["Diameter", "50,724 km"],
      ["Moons", "28 known — incl. Titania & Oberon"],
      ["Core Temp (est.)", "≈ 5,000 °C"],
      ["Cloud-top Temp", "≈ −224 °C — coldest atmosphere in the system"],
      ["Mass", "8.68 × 10²⁵ kg"],
      ["Surface Gravity", "8.69 m/s²"],
    ],
  },
  {
    id: "neptune",
    type: "PLANET VIII",
    name: "NEPTUNE",
    tagline: "The windiest world — supersonic storms at the edge of the known planets.",
    classification: "ICE GIANT // FAR SYSTEM",
    color: 0x3d5ee1,
    emissive: 0x0c1640,
    size: 2.0,
    orbitRadius: 58,
    speed: 0.18,
    note: "Winds on Neptune have been recorded near 2,100 km/h — faster than the speed of sound on Earth.",
    distanceKm: 4495.1e6,
    stats: [
      ["Distance from Sun", "4.495 billion km (30.1 AU)"],
      ["Light Travel Time", lightTime(4495.1e6)],
      ["Orbital Period", "165 years"],
      ["Day Length (rotation)", "16 hr 6 min"],
      ["Diameter", "49,244 km"],
      ["Moons", "16 known — Triton orbits backwards (retrograde)"],
      ["Core Temp (est.)", "≈ 5,400 °C"],
      ["Cloud-top Temp", "≈ −214 °C"],
      ["Mass", "1.024 × 10²⁶ kg"],
      ["Surface Gravity", "11.15 m/s²"],
    ],
  },
  {
    id: "pluto",
    type: "DWARF PLANET",
    name: "PLUTO",
    tagline: "Reclassified in 2006, still beloved — a frozen world with a heart.",
    classification: "DWARF PLANET // KUIPER BELT",
    color: 0xc9b8a8,
    emissive: 0x2a2018,
    size: 0.7,
    orbitRadius: 65,
    speed: 0.12,
    note: "Pluto and its largest moon Charon are so close in size they orbit a shared point of gravity in open space.",
    distanceKm: 5906.4e6,
    stats: [
      ["Distance from Sun", "5.906 billion km (39.5 AU)"],
      ["Light Travel Time", lightTime(5906.4e6)],
      ["Orbital Period", "248 years"],
      ["Day Length (rotation)", "6 days 9 hr"],
      ["Diameter", "2,377 km"],
      ["Moons", "5 — Charon, Styx, Nix, Kerberos, Hydra"],
      ["Surface Temp", "≈ −240 °C"],
      ["Mass", "1.31 × 10²² kg"],
      ["Surface Gravity", "0.62 m/s²"],
      ["Status", "Reclassified as dwarf planet, 2006 (IAU)"],
    ],
  },
];

const FORMULAS = [
  {
    tag: "F.01",
    title: "Light Travel Time",
    formula: "t = d / c",
    desc: "Distance (d, in km) divided by the speed of light (c ≈ 299,792.458 km/s) gives the time light — and therefore any information — takes to cross that gap.",
  },
  {
    tag: "F.02",
    title: "Kepler's Third Law",
    formula: "T² ∝ a³",
    desc: "An orbital period (T) squared is proportional to the semi-major axis (a) cubed. Farther planets take disproportionately longer to complete one orbit.",
  },
  {
    tag: "F.03",
    title: "Orbital Velocity",
    formula: "v = √(GM / r)",
    desc: "The speed needed to maintain a circular orbit at radius r around a body of mass M, where G is the gravitational constant (6.674 × 10⁻¹¹ N·m²/kg²).",
  },
  {
    tag: "F.04",
    title: "Escape Velocity",
    formula: "v = √(2GM / r)",
    desc: "The minimum speed an object needs to break free of a body's gravity entirely without further propulsion — √2 times faster than stable orbital velocity.",
  },
  {
    tag: "F.05",
    title: "Surface Gravity",
    formula: "g = GM / r²",
    desc: "Gravitational acceleration at a body's surface, derived from its mass (M) and radius (r). This is why Jupiter's gravity is 2.5× Earth's despite being mostly gas.",
  },
  {
    tag: "F.06",
    title: "Stefan–Boltzmann (Stellar Output)",
    formula: "L = 4πR²σT⁴",
    desc: "A star's luminosity (L) depends on its radius (R) and surface temperature (T) to the fourth power — a small temperature change hugely changes brightness.",
  },
];

const GALAXY_FACTS = [
  ["Galaxy Type", "Barred Spiral (SBbc)"],
  ["Diameter", "≈ 100,000 – 105,700 light-years"],
  ["Estimated Stars", "100 – 400 billion"],
  ["Age", "≈ 13.6 billion years"],
  ["Our Location", "Orion–Cygnus Arm (a minor arm)"],
  ["Distance to Galactic Center", "≈ 26,000 light-years"],
  ["Central Object", "Sagittarius A* — supermassive black hole, ≈ 4.3 million M☉"],
  ["Solar Orbital Speed", "≈ 230 km/s around the galactic center"],
  ["One Galactic Year", "≈ 225–250 million Earth years per orbit"],
  ["Disk Thickness", "≈ 1,000 light-years"],
  ["Local Group", "80+ galaxies, including Andromeda (M31)"],
  ["Future Event", "Collision with Andromeda predicted in ≈ 4.5 billion years"],
];
